# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"\"\n\x0fSlowDownRequest\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\"#\n\x10SlowDownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0eRestoreRequest\"\"\n\x0fRestoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"0\n\x14RegisterSlaveRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"(\n\x15RegisterSlaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc6\x03\n\rKeyValueStore\x12,\n\x03put\x12\x11.store.PutRequest\x1a\x12.store.PutResponse\x12,\n\x03get\x12\x11.store.GetRequest\x1a\x12.store.GetResponse\x12;\n\x08slowDown\x12\x16.store.SlowDownRequest\x1a\x17.store.SlowDownResponse\x12\x38\n\x07restore\x12\x15.store.RestoreRequest\x1a\x16.store.RestoreResponse\x12\x30\n\x07votePut\x12\x11.store.PutRequest\x1a\x12.store.PutResponse\x12\x32\n\tcommitPut\x12\x11.store.PutRequest\x1a\x12.store.PutResponse\x12\x30\n\x07voteGet\x12\x11.store.GetRequest\x1a\x12.store.GetResponse\x12J\n\rregisterSlave\x12\x1b.store.RegisterSlaveRequest\x1a\x1c.store.RegisterSlaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=22
  _globals['_PUTREQUEST']._serialized_end=62
  _globals['_PUTRESPONSE']._serialized_start=64
  _globals['_PUTRESPONSE']._serialized_end=94
  _globals['_GETREQUEST']._serialized_start=96
  _globals['_GETREQUEST']._serialized_end=121
  _globals['_GETRESPONSE']._serialized_start=123
  _globals['_GETRESPONSE']._serialized_end=166
  _globals['_SLOWDOWNREQUEST']._serialized_start=168
  _globals['_SLOWDOWNREQUEST']._serialized_end=202
  _globals['_SLOWDOWNRESPONSE']._serialized_start=204
  _globals['_SLOWDOWNRESPONSE']._serialized_end=239
  _globals['_RESTOREREQUEST']._serialized_start=241
  _globals['_RESTOREREQUEST']._serialized_end=257
  _globals['_RESTORERESPONSE']._serialized_start=259
  _globals['_RESTORERESPONSE']._serialized_end=293
  _globals['_REGISTERSLAVEREQUEST']._serialized_start=295
  _globals['_REGISTERSLAVEREQUEST']._serialized_end=343
  _globals['_REGISTERSLAVERESPONSE']._serialized_start=345
  _globals['_REGISTERSLAVERESPONSE']._serialized_end=385
  _globals['_KEYVALUESTORE']._serialized_start=388
  _globals['_KEYVALUESTORE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
